name: Publish Release

on:
  push:
    tags:
      - 'v*'

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository 
      uses: actions/checkout@v2
    - name: Zip files
      uses: papeloto/action-zip@v1
      with:
        files: background.js manifest.json icons/ LICENSE
        dest: pixiv-favorites.zip

    - name: Set output for tags
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    - name: Create Draft Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.vars.outputs.tag }}
        release_name: Pixiv Favorites
        draft: true
        prerelease: false
    - uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./pixiv-favorites.zip
        asset_name: pixiv-favorites.zip
        asset_content_type: application/zip
    - uses: eregon/publish-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ steps.create_release.outputs.id }}